### ISSUE TITLE
push dice to roll

### ISSUE THREAD

**Issue by Reventless** [PurHur/rollone#5]
Hey,

Philipp wants to roll the dice by tapping it.

**Comment by Reventless** [comment]
Roll by shaking a smartphone or smartwatch.

**Comment by Reventless** [comment]
have different dice to select from

**Comment by Reventless** [comment]
D6 showing wrong numbers on dice counter parts on dice need to sum to seven

**Comment by PurHur** [comment]
This issue contains more than one feature request. The first feature request is resolved. Please open one issue for each feature.
